version: '3.4'

services:
  one-time:
    labels: 
      shipyard.job: true
    build: '.'
    command: 'sh date.sh'

  cronjob:
    labels:
      shipyard.job: true
      shipyard.job.schedule: '*/2 * * * *'
    build: '.'
    command: 'sh date.sh'

  http-echo: 
    labels:
      shipyard.route: '/'
    image: jmalloc/echo-server
    ports:
      - '8080'
